### ISSUE TITLE
Makefile details

### ISSUE THREAD

**Issue by jimrthy** [lwes/lwes#2]
Following the README instructions, running make on linux got down to linking with libtool, then "Making all in tests". It entered the test directory, then line 1025 has this error:
*** unterminated variable reference. Stop.
and make exited with Error 1.

Adding a \ to the end of line 1025 in tests/Makefile cleared up that error, but produced what seems like a bunch of circular dependencies that get dropped. And led to this error:

make[2]: *** No rule to make target: `testlwes-calculate-max-event-size)', needed by `testlwes-event-testing-emitter'. Stop.
Then make[2] leaves that directory, so does make[1] (check-am) with Error 2, and make (check-recursive) with Error 1.

It seems like it's likely just a minor detail in the autotools chain. Maybe some silly incompatibility between versions (I'm using GNU make 3.82). I haven't gone any further yet, but I suspect it doesn't impact anything except actually running unit tests.

Is there some better forum for reporting this sort of thing?

**Comment by djnym** [comment]
I'm pretty sure this is ancient and I've not seen this happen, so closing.
